services:
  saboga-frontend:
    image: registry.gitlab.com/ruberhauptmann/saboga-frontend/saboga-frontend:latest
    container_name: saboga-frontend
    labels:
      - "traefik.http.routers.saboga-frontend.rule=Host(`saboga.tjarksievers.de`)"
      - "traefik.http.routers.saboga-frontend.tls=true"
      - "traefik.http.routers.saboga-frontend.tls.certresolver=certresolver"
    depends_on:
      - reverse-proxy
      - saboga-api
    networks:
      - saboga-api
      - reverse-proxy
