version: '3.8'

services:
  frontend:
    image: registry.gitlab.com/ruberhauptmann/saboga-frontend/saboga-frontend:latest
    container_name: saboga-frontend
    depends_on:
      - nginx-proxy
    environment:
      - VIRTUAL_HOST=saboga.tjarksievers.de
      - VIRTUAL_PATH=/
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=saboga.tjarksievers.de
      - LETSENCRYPT_EMAIL=tjark.sievers@outlook.de
    networks:
      - saboga-api
      - nginx-proxy

networks:
  saboga-api:
