version: '3.8'

services:
  frontend:
    image: registry.gitlab.com/ruberhauptmann/saboga-frontend/saboga-frontend:latest
    container_name: saboga-frontend
    labels:
      - "traefik.http.routers.frontend.rule=Host(`saboga.tjarksievers.de`)"
    depends_on:
      - reverse-proxy
    networks:
      - saboga-api
      - reverse-proxy

networks:
  saboga-api:
