services:
  saboga-frontend:
    image: ghcr.io/ruberhauptmann/saboga-frontend:0.0.2
    container_name: saboga-frontend
    labels:
      - "traefik.http.routers.saboga-frontend.rule=Host(`saboga.tjarksievers.de`)"
      - "traefik.http.routers.saboga-frontend.tls=true"
      - "traefik.http.routers.saboga-frontend.tls.certresolver=certresolver"
    depends_on:
      - reverse-proxy
      - saboga-api
    networks:
      - reverse-proxy
      - saboga-api

  saboga-api:
    image: ghcr.io/ruberhauptmann/saboga-api:0.0.27
    container_name: saboga-api
    command: uvicorn sabogaapi.main:app --root-path /api --workers 1 --host 0.0.0.0 --port 8000
    labels:
      - "traefik.http.routers.saboga-api.rule=Host(`saboga.tjarksievers.de`) && PathPrefix(`/api`)"
      - "traefik.http.routers.saboga-api.tls=true"
      - "traefik.http.routers.saboga-api.tls.certresolver=certresolver"
    environment:
      MONGODB_API_USER: ${MONGODB_API_USER}
    volumes:
      - saboga_api_static:/app/static
    expose:
      - "8000"
    depends_on:
      - reverse-proxy
    networks:
      - reverse-proxy
      - saboga-api

  saboga-database:
    image: mongo:jammy
    container_name: saboga-database
    volumes:
      - saboga_db_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: siteUserAdmin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_SITEUSERADMIN}
    networks:
      - saboga-api

  saboga-database-backup:
    image: stefanprodan/mgob
    container_name: saboga-mgob
    volumes:
      - /mgob/config:/config
      - /mgob/storage:/storage
      - /mgob/tmp:/tmp
      - /mgob/data:/data
    networks:
      - saboga-api

volumes:
  saboga_db_data:
  saboga_api_static:

networks:
  saboga-api:
    driver: bridge
    internal: true
