services:
  saboga-frontend:
    image: ghcr.io/ruberhauptmann/saboga-frontend:0.0.8
    container_name: saboga-frontend
    labels:
      - "traefik.http.routers.saboga-frontend.rule=Host(`saboga.tjarksievers.de`)"
      - "traefik.http.routers.saboga-frontend.tls=true"
      - "traefik.http.routers.saboga-frontend.tls.certresolver=certresolver"
    depends_on:
      - reverse-proxy
      - saboga-api
    restart: always
    networks:
      - reverse-proxy
      - saboga-api

  saboga-api:
    image: ghcr.io/ruberhauptmann/saboga-api:0.0.49
    container_name: saboga-api
    labels:
      - "traefik.http.routers.saboga-api.rule=Host(`saboga.tjarksievers.de`) && PathPrefix(`/api`)"
      - "traefik.http.routers.saboga-api.tls=true"
      - "traefik.http.routers.saboga-api.tls.certresolver=certresolver"
      - "traefik.http.routers.saboga-api.middlewares=strip-api-prefix"
      - "traefik.http.middlewares.strip-api-prefix.stripPrefix.prefixes=/api"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      BGG_USERNAME: ${BGG_USERNAME}
      BGG_PASSWORD: ${BGG_PASSWORD}
    volumes:
      - saboga_api_static:/static
      - saboga_api_img:/img
    restart: always
    expose:
      - "8000"
    depends_on:
      - reverse-proxy
    networks:
      - reverse-proxy
      - saboga-api
      - loki

  saboga-database:
    image: mongo:8.0-noble
    container_name: saboga-database
    volumes:
      - saboga_db_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: siteUserAdmin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_SITEUSERADMIN}
    restart: always
    networks:
      - saboga-api

  saboga-database-backup:
    image: stefanprodan/mgob
    container_name: saboga-mgob
    restart: always
    volumes:
      - /mgob/config:/config
      - /mgob/storage:/storage
      - /mgob/tmp:/tmp
      - /mgob/data:/data
    networks:
      - saboga-api

volumes:
  saboga_db_data:
  saboga_api_static:
  saboga_api_img:

networks:
  saboga-api:
    driver: bridge
    internal: true
