server {
    listen 80;

    # serve collected static files
    location /api/static/ {
        alias /usr/share/nginx/html/static/;
        expires max;
        add_header Cache-Control "public";
    }

    # optional: serve media if you have any
    location /api/img/ {
        alias /usr/share/nginx/html/img/;
        expires max;
        add_header Cache-Control "public";
    }
}