stages:
  - build
  #- test
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  INDEX_IMAGE_TAG: $CI_REGISTRY_IMAGE/tjarksievers.de:latest

services:
  - docker:20-dind

build-index:
  image: docker:20
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $INDEX_IMAGE_TAG:latest || true
    - docker build --cache-from $INDEX_IMAGE_TAG:latest --pull -t $INDEX_IMAGE_TAG pages/tjarksievers.de/
    - docker push $INDEX_IMAGE_TAG
  tags:
    - docker

#test-index:
#  image: $INDEX_IMAGE_TAG
#  stage: test
#  script:
#    - echo "test not yet implemented"
#  tags:
#    - docker

deploy:
  image: docker:20
  stage: deploy
  before_script:
    - unset DOCKER_HOST
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker context import production production.dockercontext
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - cat host_key.txt >> ~/.ssh/known_hosts
  script:
    - > 
      docker --context=production compose
      -f docker-compose.yml
      -f pages/tjarksievers.de/docker-compose.yml
      -f pages/grafana.tjarksievers.de/docker-compose.yml
      -f pages/influx.tjarksievers.de/docker-compose.yml
      -f pages/budget.tjarksievers.de/docker-compose.yml
      down
    - >
      docker --context=production compose
      -f docker-compose.yml
      -f pages/tjarksievers.de/docker-compose.yml
      -f pages/grafana.tjarksievers.de/docker-compose.yml
      -f pages/influx.tjarksievers.de/docker-compose.yml
      -f pages/budget.tjarksievers.de/docker-compose.yml
      pull
    - > 
      docker --context=production compose 
      -f docker-compose.yml
      -f pages/tjarksievers.de/docker-compose.yml
      -f pages/grafana.tjarksievers.de/docker-compose.yml
      -f pages/influx.tjarksievers.de/docker-compose.yml
      -f pages/budget.tjarksievers.de/docker-compose.yml
      up -d
  tags:
    - docker
  only:
    - main
