stages:
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  INDEX_IMAGE_TAG: $CI_REGISTRY_IMAGE/tjarksievers.de:latest

services:
  - docker:20-dind


deploy:
  image: docker:20
  stage: deploy
  before_script:
    - unset DOCKER_HOST
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker context import production production.dockercontext
  script:
    - > 
      docker --context=production compose
      -f docker-compose.yml
      -f pages/tjarksievers.de/docker-compose.yml
      -f pages/budget.tjarksievers.de/docker-compose.yml
      -f pages/api.saboga.tjarksievers.de/docker-compose.yml
      -f pages/saboga.tjarksievers.de/docker-compose.yml
      stop
    - >
      docker --context=production compose
      -f docker-compose.yml
      -f pages/tjarksievers.de/docker-compose.yml
      -f pages/budget.tjarksievers.de/docker-compose.yml
      -f pages/api.saboga.tjarksievers.de/docker-compose.yml
      -f pages/saboga.tjarksievers.de/docker-compose.yml
      pull
    - > 
      docker --context=production compose
      -f docker-compose.yml
      -f pages/tjarksievers.de/docker-compose.yml
      -f pages/budget.tjarksievers.de/docker-compose.yml
      -f pages/api.saboga.tjarksievers.de/docker-compose.yml
      -f pages/saboga.tjarksievers.de/docker-compose.yml
      up -d --build
    - docker --context=production exec saboga-api alembic upgrade head
  only:
    - main
