services:
  reverse-proxy:
    image: traefik:v3.0
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - acme-data:/acme.json
    configs:
      - source: traefik_config
        target: /etc/traefik/traefik.yml
      - source: dynamic_config
        target: /etc/traefik/dynamic.yml
    networks:
      - reverse-proxy

configs:
  traefik_config:
    file: ./traefik.yml
  dynamic_config:
    file: ./dynamic.yml

volumes:
  acme-data:

networks:
  reverse-proxy:
    driver: bridge
