version: '3'

services:
  reverse-proxy:
    image: traefik:v2.11
    container_name: reverse-proxy
    command:
      - "--api.dashboard=true"
    labels:
      - "traefik.http.routers.dashboard.rule=Host(`traefik.tjarksievers.de`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=tjark:$$2y$$05$$jPwGv8D/GmohOqXvHAT43On2jdW3ToA1QD45jIjj4wB/RTJD2ZWHe"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    driver: bridge