services:
  reverse-proxy:
    image: traefik:v3.0
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - acme-data:/acme-data
      - /tmp/traefik.yml:/etc/traefik/traefik.yml:ro
      - /tmp/dynamic.yml:/etc/traefik/dynamic.yml:ro
    networks:
      - reverse-proxy
      - nextcloud-aio

volumes:
  acme-data:

networks:
  reverse-proxy:
    driver: bridge
  nextcloud-aio:
    external: true
