services:
  saboga-api:
    image: ghcr.io/ruberhauptmann/saboga-api:latest
    container_name: saboga-api
    labels:
      - "traefik.http.routers.saboga-api.rule=Host(`api.saboga.tjarksievers.de`)"
      - "traefik.http.routers.saboga-api.tls=true"
      - "traefik.http.routers.saboga-api.tls.certresolver=certresolver"
    expose:
      - "8000"
    depends_on:
      - reverse-proxy
    networks:
      - saboga-api
      - reverse-proxy

  database:
    image: mongo:jammy
    container_name: saboga-database
    volumes:
      - saboga_db_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: siteUserAdmin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_SITEUSERADMIN}
    networks:
      - saboga-api


    database-backup:
      image: stefanprodan/mgob
      name: saboga-mgob
      volumes:
        - /mgob/config:/config
        - /mgob/storage:/storage
        - /mgob/tmp:/tmp
        - /mgob/data:/data
      environment:
        BACKUP__TARGET_PASSWORD: ${MONGODB_BACKUP}
      networks:
        - saboga-api

volumes:
  saboga_db_data:
networks:
  saboga-api:
    name: saboga-api
    driver: bridge
