services:
  saboga-api:
    image: ghcr.io/ruberhauptmann/saboga-api:latest
    container_name: saboga-api
    labels:
      - "traefik.http.routers.saboga-api.rule=Host(`api.saboga.tjarksievers.de`)"
      - "traefik.http.routers.saboga-api.tls=true"
      - "traefik.http.routers.saboga-api.tls.certresolver=certresolver"
    expose:
      - "8000"
    depends_on:
      - reverse-proxy
    env_file:
      - pages/api.saboga.tjarksievers.de/.env
    networks:
      - saboga-api
      - reverse-proxy

  database:
    image: mongo:jammy
    container_name: saboga-database
    volumes:
      - mongodb-data:/data/db
    env_file:
      - pages/api.saboga.tjarksievers.de/.env
    networks:
      - saboga-api

volumes:
  mongodb-data:
networks:
  saboga-api:
    name: saboga-api
    driver: bridge
