version: '3.8'

services:
  api:
    image: registry.gitlab.com/ruberhauptmann/sabogaapi/sabogaapi:latest
    container_name: saboga-api
    depends_on:
      - nginx-proxy
    environment:
      - VIRTUAL_HOST=api.saboga.tjarksievers.de
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=api.saboga.tjarksievers.de
      - LETSENCRYPT_EMAIL=tjark.sievers@outlook.de
    env_file:
      - pages/api.saboga.tjarksievers.de/.env
    networks:
      - saboga-api
      - nginx-proxy

  database:
    image: mariadb:latest
    container_name: saboga-database
    volumes:
      - mariadb-data:/var/lib/mysql
    env_file:
      - pages/api.saboga.tjarksievers.de/.env
    networks:
      - saboga-api

volumes:
  mariadb-data:
networks:
  saboga-api:
    name: saboga-api
    driver: bridge
