version: '3'
services:
  actual_server:
    image: actualbudget/actual-server:latest
    container_name: budget-tjarksievers-de
    labels:
      - "traefik.http.routers.actual_server.rule=Host('budget.tjarksievers.de')"
    networks:
      - reverse-proxy
    depends_on:
      - reverse-proxy
    volumes:
      - actualbudget_data:/data
    restart: unless-stopped

volumes:
  actualbudget_data: {}
