version: '3'
services:
  actual_server:
    image: actualbudget/actual-server:latest
    container_name: budget-tjarksievers-de
    networks:
      - reverse-proxy
    environment:
      - VIRTUAL_HOST=budget.tjarksievers.de
      - VIRTUAL_PORT=5006
      - LETSENCRYPT_HOST=budget.tjarksievers.de
      - LETSENCRYPT_EMAIL=tjark.sievers@outlook.de
    depends_on:
      - reverse-proxy
    volumes:
      - actualbudget_data:/data
    restart: unless-stopped

volumes:
  actualbudget_data: {}
