services:
  actual_server:
    image: actualbudget/actual-server:edge
    container_name: budget-tjarksievers-de
    labels:
      - "traefik.http.routers.actual_server.rule=Host(`budget.tjarksievers.de`)"
      - "traefik.http.routers.actual_server.tls=true"
      - "traefik.http.routers.actual_server.tls.certresolver=certresolver"
    networks:
      - reverse-proxy
    depends_on:
      - reverse-proxy
    volumes:
      - actualbudget_data:/data
    restart: always

volumes:
  actualbudget_data: {}
