baseURL = "https://tjarksievers.de/"
title = "Tjark Sievers"
theme = "sunflower"
paginate = 8
languageCode = "en"
DefaultContentLanguage = "en"
ignoreFiles = ['README.md$']
summaryLength = 20

copyright = "Copyright © 2024, Tjark Sievers, all rights reserved."

[Params]
  mainSections = ["projects"]
  homepageSections = ["posts"]
  favicon = "favicon.svg"
  profile = "profile.webp"
  hero = "sunset.webp"
  abstract = """
    I'm a Physics master student currently working on my master thesis, a joint project
    between Prof. Tim Wehling at Universität Hamburg and Prof. Annica Black-Schaffer at Uppsala University.
    My research interest is the theory of superconductivity in strongly correlated electron systems.
    """
  bgg_username = "ourkindofart"
  bgg_title = "Last boardgames played"

[Params.social.orcid]
  link = "https://orcid.org/0000-0002-4365-7729"
[Params.social.email]
  link = "tsievers@physnet.uni-hamburg.de"
[Params.social.github]
  link = "https://github.com/Ruberhauptmann"
[Params.social.linkedin]
  link = "https://linkedin.com/in/tjark-sievers-5b95822b9"
[Params.social.gpg]
  link = "/gpg.txt"

[Params.cv]
  url = "/cv/"
  download = "https://raw.githubusercontent.com/Ruberhauptmann/cv/main/TjarkSieversAcademicCV_en.pdf"
  general = true
  education = true
  schools_conferences = true
  work_experience = true
  #publications = true
  technical_skills = true

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[frontmatter]
  date = ['date_finished', ':default']

[menu]
#[[menu.main]]
#  name = "Publications"
#  url = "/publications"
#  weight = -130
[[menu.main]]
  name = "CV"
  url = "/cv"
  weight = -120
[[menu.main]]
  name = "Projects"
  url = "/categories/project-showcases"
  weight = -110
[[menu.main]]
  name = "Lecture Notes"
  url = "/lecture-notes"
  weight = -100
[[menu.main]]
  name = "About"
  url = "/about"
  weight = 0
