baseURL = "https://tjarksievers.de/"
title = "Tjark Sievers"
theme = "sunflower"
paginate = 8
languageCode = "en"
DefaultContentLanguage = "en"
ignoreFiles = ['README.md$']
summaryLength = 20

copyright = "Copyright © 2025, Tjark Sievers, all rights reserved."

[Params]
  mainSections = ["projects"]
  homepageSections = ["posts", "boardgames"]
  favicon = "favicon.svg"
  profile = "profile.webp"
  hero = "sunset.webp"
  abstract = """
    Physicist turned developer. Currently working as a software engineer at altona diagnostics.
    """
  bgg_username = "ourkindofart"
  bgg_title = "Last boardgames played"
  impressum = "impressum"

[Params.social.email]
  link = "tsievers@physnet.uni-hamburg.de"
[Params.social.github]
  link = "https://github.com/Ruberhauptmann"
[Params.social.gpg]
  link = "/gpg.txt"

[Params.cv]
  url = "/cv/"
  download = "https://raw.githubusercontent.com/Ruberhauptmann/cv/main/TjarkSieversAcademicCV_en.pdf"
  general = true
  education = true
  schools_conferences = true
  work_experience = true
  #publications = true
  technical_skills = true

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[frontmatter]
  date = ['date_finished', ':default']

[menu]
#[[menu.main]]
#  name = "Publications"
#  url = "/publications"
#  weight = -130
[[menu.main]]
  name = "CV"
  url = "/cv"
  weight = -120
[[menu.main]]
  name = "Projects"
  url = "/categories/project-showcases"
  weight = -110
[[menu.main]]
  name = "Lecture Notes"
  url = "/lecture-notes"
  weight = -100
[[menu.main]]
  name = "About"
  url = "/about"
  weight = 0
