services:
  tjarksievers-de:
    build: pages/tjarksievers.de
    container_name: tjarksievers-de
    labels:
      - "traefik.http.routers.tjarksievers-de.rule=Host(`tjarksievers.de`)"
      - "traefik.http.routers.tjarksievers-de.tls=true"
      - "traefik.http.routers.tjarksievers-de.tls.certresolver=certresolver"
    restart: always
    networks:
      - reverse-proxy
    depends_on:
      - reverse-proxy
