version: '3'

services:
  tjarksievers-de:
    image: $INDEX_IMAGE_TAG
    container_name: tjarksievers-de
    labels:
      - "traefik.http.routers.tjarksievers-de.rule=Host(`tjarksievers.de`)"
    networks:
      - reverse-proxy
    depends_on:
      - reverse-proxy
