version: '3'

services:
  tjarksievers-de:
    image: $INDEX_IMAGE_TAG
    container_name: tjarksievers-de
    networks:
      - reverse-proxy
    environment:
      - VIRTUAL_HOST=tjarksievers.de
      - LETSENCRYPT_HOST=tjarksievers.de
      - LETSENCRYPT_EMAIL=tjark.sievers@outlook.de
    depends_on:
      - reverse-proxy
