services:
  tjarksievers-de:
    build: pages/tjarksievers.de
    container_name: tjarksievers-de
    labels:
      - "traefik.http.routers.tjarksievers-de.rule=Host(`tjarksievers.de`)"
      - "traefik.http.routers.tjarksievers-de.tls=true"
      - "traefik.http.routers.tjarksievers-de.tls.certresolver=certresolver"
      - "traefik.http.routers.tjarksievers-de.middlewares=compress, http-cache"
      - "traefik.http.middlewares.compress.compress=true"
      - "traefik.http.middlewares.http-cache.plugin.httpCache.maxTtl=2592000"
    restart: always
    networks:
      - reverse-proxy
    depends_on:
      - reverse-proxy
