name: Deployment

on:
  push:
    branches:
    - main

jobs:
  deployment:
    environment:
      name: production
      url: https://tjarksievers.de
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ssh-key: ${{ secrets.LECTURE_NOTES_DEPLOY_KEY }}
        submodules: 'recursive'
    - name: Setup ssh auth
      run: >
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null &&
        mkdir -p ~/.ssh &&
        chmod 700 ~/.ssh &&
        ssh-add - <<< "$SSH_PRIVATE_KEY" &&
        cat host_key.txt >> ~/.ssh/known_hosts
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    - name: Import docker contect to deploy
      run: docker context import production production.dockercontext
    - name: Run deployment
      run: ./deploy.sh
      env:
        MONGODB_SITEUSERADMIN: ${{ secrets.MONGODB_SITEUSERADMIN }}
        MONGODB_BACKUP: ${{ secrets.MONGODB_BACKUP }}
        MONGODB_API_USER: ${ secrets.MONGODB_API_USER }}
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
