name: Deployment

on:
  push:
    branches:
    - main

jobs:
  deployment:
    environment:
      name: production
      url: https://tjarksievers.de
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup ssh auth
      run: >
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        eval $(ssh-agent -s) &&
        mkdir -p ~/.ssh &&
        chmod 700 ~/.ssh &&
        ssh-add - <<< "$SSH_PRIVATE_KEY" &&
        cat host_key.txt >> ~/.ssh/known_hosts
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    - name: Import docker contect to deploy
      run: docker context import production production.dockercontext
    - name: Stop containers
      run: >
        docker --context=production compose
        -f docker-compose.yml 
        stop
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    - name: Stop containers
      run: >
        docker --context=production compose
        -f docker-compose.yml 
        pull
    - name: Start containers
      run: >
        docker --context=production compose
        -f docker-compose.yml 
        up -d build
